---
- name: Prepare project catalog
  block:
    - name: Copy application directory to remote VM
      copy:
        src: ../nodeApp/
        dest: "{{ application_home_dir }}/"
        owner: "{{ local_ansible_local_username }}"
        group: "{{ local_ansible_local_username }}"
        mode: '0755'
      register: application_deploy_result
      
    - name: Ensure correct permissions on the application directory
      file:
        path: "{{ application_home_dir }}"
        state: directory
        owner: "{{ local_ansible_local_username }}"
        mode: '0755'
        recurse: yes