- name: Log in to GHCR (local build)
  community.docker.docker_login:
    registry_url: ghcr.io
    username: "{{ github_user }}"
    password: "{{ github_token }}"
  delegate_to: localhost
  run_once: true

- name: Build Node.js app image locally
  ansible.builtin.shell: docker build -t ghcr.io/hkarol-10/portfolio-app:latest ../nodeApp
  delegate_to: localhost
  run_once: true

- name: Push Node.js app image to GHCR
  ansible.builtin.shell: docker push ghcr.io/hkarol-10/portfolio-app:latest
  delegate_to: localhost
  run_once: true