name: Monitoring tool build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_app_image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./cloudrun/monitoring-tool
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/monitoring-tool:latest