name: Terraform infrastructure watcher

on:
  schedule:
    - cron: '0 4 * * *'  # 06:00 Poland (CEST), 05:00 Poland (CET)
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
      TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
      TF_VAR_zone: ${{ secrets.TF_VAR_ZONE }}
      TF_VAR_app_vm_name: ${{ secrets.TF_VAR_APP_VM_NAME }}
      TF_VAR_elk_vm_name: ${{ secrets.TF_VAR_ELK_VM_NAME }}
      TF_VAR_allowed_ssh_cidr: ${{ secrets.TF_VAR_ALLOWED_SSH_CIDR }}
      TF_VAR_allowed_ssh_port: ${{ secrets.TF_VAR_ALLOWED_SSH_PORT }}
      TF_VAR_cloudflare_zone_id: ${{ secrets.TF_VAR_CLOUDFLARE_ZONE_ID }}
      TF_VAR_cloudflare_api_token: ${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -input=false -no-color -detailed-exitcode > plan.out

      - name: Check for changes
        run: |
         if grep -q 'Your infrastructure matches the configuration.' plan.out; then
              echo "No changes detected, ending run with success!"
            else
              echo "Changes detected!! FIX required, check and plan the changes locally!"
              exit 1
            fi     