# Disabled due to public repo and logs accesability for everyone
# The below code is working and tested in private repo
# It generates CVE vulnerability report for Docker image built from the nodeApp folder
# To enable it, just remove the leading # from each line ONLY ON PRIVATE REPO!

#name: Trivy vulnerability scan
#
#on:
#  push:
#    branches:
#      - main
#  workflow_dispatch:
#
#jobs:
#  testing_build_app_image:
#    name: Build, scan & push Docker image
#    runs-on: ubuntu-latest
#
#    permissions:
#      packages: write
#      contents: read
#      security-events: write
#
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v3
#
#      - name: Log in to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build Docker image locally
#        run: docker build -t portfolio-app:latest ./nodeApp
#
#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@0.20.0
#        with:
#          image-ref: portfolio-app:latest
#          format: table
#          exit-code: 0